### ISSUE TITLE
Method Not Allowed still returning HTML

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#112]
We need to ensure that we only return JSON responses. In the case of `405 Method Not Allowed`, we're still returning HTML. We need to add a handler in `app/errors/handlers.py` for handling `405` errors, and it should return a standardized response with JSON describing that the method is not allowed.

To avoid merge conflicts and double work, please wait until #110 is merged to start on this issue.

**Comment by phongvdoan** [comment]
when adding handler in handlers.py, does the standardize_response function need to be updated with the 405 error in utils.py?

**Comment by aaron-suarez** [comment]
Yes, but also, a handler has to be added to `app/errors/handlers.py` to catch the 405 error and then call `standardize_response` with a 405 status code

**Comment by aaron-suarez** [comment]
closed in #119
