### ISSUE TITLE
Testing should be decoupled from specific response strings

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#116]
Per this comment https://github.com/OperationCode/resources_api/pull/111#discussion_r266947365

Some tests basically test the exact string returned from the server rather than the fact that the exception handler is called. This can be problematic if we ever need to change those strings and the exception is still called fine (meaning the test should pass). An example of this is here:
https://github.com/OperationCode/resources_api/blob/10c20bf8d5df5ee4b387eb79da6bf75ae90d9b83/tests/unit/test_routes.py#L299

There are several instances of this throughout the tests.

**Comment by RanadeepPolavarapu** [comment]
Hello, I could tackle this.
