### ISSUE TITLE
Remove MultipleResultsFound condition from routes

### ISSUE THREAD

**Issue by Qlwentt** [OperationCode/resources_api#126]
**Note: I will complete this task**

In many routes we are throwing an exception if multiple results are found for a particular id. 

This doesn't seem possible because ids should be a unique identifier. @aaron-suarez has not been able to reproduce this in tests. Therefore we're just going to remove this condition from the routes. 

See https://github.com/OperationCode/resources_api/pull/125#discussion_r272813743 for more details

**Comment by aaron-suarez** [comment]
Closed via #127
