### ISSUE TITLE
No setup instructions for Windows

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#13]
The README explains the development setup steps for Mac, but not for Windows. Eventually, we want to move to some type of Docker setup, but for the moment, it would be helpful to describe the steps to get this working for contributors working on Windows machines.

**Comment by heavysaturn** [comment]
I could probably add this, but yeah using docker and docker-compose would reduce the setup to:

1. install docker and docker-compose
2. fork this repo
3. clone your fork
4. run `docker-compose up` in the clone folder
5. if you're on windows or mac, run `docker-machine ip` to figure out what your docker ip is. if you're on *nix, you can just connect to localhost instead.
6. server is now running! go to `http://YOUR_DOCKER_IP:5000/api/v1/` to test.

steps 5 and 6 could also be displayed when you run `docker-compose up` if we're a bit clever about it. we could detect the OS, run the command to get the ip if necessary, and build a print that tells the user where exactly the server is running, just like flask normally does when you use `flask run`

**Comment by heavysaturn** [comment]
it'd be _even better_ if we managed to get this to play well with pipenv as well, using docker-compose only for the postgres database and pipenv to build the venv, install the packages from pip, export the environment variables, and expose simple scripts the user could run.

- `pipenv run init` to set up the database with the initial data and make everything ready to run. here, the environment variables could be set up in such a way that windows and mac users would connect to a remote postgres located on the docker ip.
- `pipenv run start` to run the flask app,
- `pipenv run lint` to lint the app
- `pipenv run test` to run all the unit tests and show results
- `pipenv run hook` to create a pre-commit hook that lints and runs all tests before allowing a commit.

**Comment by aaron-suarez** [comment]
We can do a few of those with click commands though, right? We already have some of that for the migrate/upgrade for example. Does pipenv offer some special benefit?

**Comment by heavysaturn** [comment]
basically pipenv is a marriage of requirements.txt, pip and venv. You make a `Pipfile` that says which packages to use, which version of python to use for the venv, and as a bonus feature you can define these run scripts.

The user never has to create a venv, activate the venv, install packages (we can remove `requirements.txt` completely), or anything else. they just sync the pipenv, and then use the scripts to interact with stuff inside it. if they need access to the venv shell, there's a `pipenv shell` command for that too

**Comment by heavysaturn** [comment]
and while click commands are good for executing arbitrary python code, pipenv run scripts are really just for running terminal commands inside the venv, nothing more. I would argue that the two can work quite well together. You'd make click commands for more complex stuff that you need python for, and use pipenv run to execute those click commands from outside the venv.

**Comment by wimo7083** [comment]
I have no problem with pipenv, (except it's slow). 

I just need to find time to implement docker but I'm hoping that I can do it this weekend.

**Comment by aaron-suarez** [comment]
Fixed by #47
