### ISSUE TITLE
Push docker image to dockerhub on merge to master

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/resources_api#139]
When we merge to master and CI passes we need push to dockerhub and tag appropriately so our infrastructure can update the running pod.

We also want to tag both staging and production on merge to master for the most recent build. 

Later we can investigate promotion strategies.

**Comment by aaron-suarez** [comment]
This will probably follow the same pattern as https://github.com/OperationCode/operationcode-pybot/pull/68
