### ISSUE TITLE
Integrate with Algolia

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#144]
Once we make an Open Source plan with their service, we can integrate with Algolia for the search endpoint.

**Comment by wimo7083** [comment]
What's the use case and reasoning for this? I know you talked about this, but can we get that transferred into this.

**Comment by aaron-suarez** [comment]
Algolia provides a way to create indexes on our data. When a client sends a given string, Algolia will allow us to search all of the indexed data for matches, then it will return results that are most relevant to the search. Relevancy will be improved over time based on Algolia's algorithms. The `/search` endpoint will need to rely on these indexes to return relevant results.

**Comment by aaron-suarez** [comment]
This is fixed by https://github.com/OperationCode/resources_api/pull/150

**Comment by aaron-suarez** [comment]
Closed by #172
