### ISSUE TITLE
Issues concerning data in resources.yml (and, by extension, the DB)

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#18]
The following are known issues that exist with the data:

- [ ] Some (many?) resources have "multiple" as a language, instead of listing out the multiple languages
- [ ] Some categories only have 1 to 3 resources. If it can be combined with another category, it should be combined
- [ ] Some categories are repeats of other categories and should be combined into one. e.g., Web Dev and Web Development (This particular example may have already been taken care of, but we should be on the look out for things like this)

**Comment by wimo7083** [comment]
Closing for three separate detailed issues.
