### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#184]
There is almost no documentation on how to use the API. Might be useful to flesh out the Wiki for this repo with actual docs, or perhaps even document it using [OpenAPI](https://swagger.io/docs/specification/about/).

**Comment by soris-codes** [comment]
I would love to jump in and help with this @aaron-suarez. Any guidance for formatting, what we'd need to include, etc?

**Comment by aaron-suarez** [comment]
We definitely need to include instructions on how to authenticate with the API (how to get your API token, how to use it, which routes need it).

It should describe each route, what acceptable query parameters are and what acceptable body params are.

I'm not too worried about the formatting at this point, something is better than nothing after all. We can always iterate on it and make it better as we go along. That being said, if we use OpenAPI, we can use [Redoc](https://github.com/Redocly/redoc) to generate the docs for us from the swagger files and not have to worry about bickering over formatting.

**Comment by soris-codes** [comment]
Going to read about OpenAPI and Redoc today.

**Comment by aaron-suarez** [comment]
Docs are live at https://resources.operationcode.org/ 🎉
