### ISSUE TITLE
Click command to download data from the database

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#187]
In order to provide a granular backup of the data in the db, we need a way to save in a text file (or series of files) all of the data that's in the database. This way, should anything happen to any records in the prod database, we have a way of restoring that data down to the affected record(s).

The click command should connect to the database and download all of the data into text files in the docker container.

**Comment by Kshitij09** [comment]
Is this issue still open ?

**Comment by aaron-suarez** [comment]
I was going to work on it but it's been 3 months and I haven't allocated the time to work on this that I originally intended. If you can do it, go for it. If not, no big deal

**Comment by Kshitij09** [comment]
Okay. Thanks!
