### ISSUE TITLE
Add filtering to search endpoint

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#194]
We might want to be able to search for "python" but also filter based on "paid=false". Right now, I believe our filters work for the `/resources` endpoint but not the search endpoint.

**Examples:**

This currently works to filter for the `/resources` endpoint:
```
http://127.0.0.1:5000/api/v1/resources?language=python&category=books&paid=false
```

Doing that will filter down to just python books that are free. When using the search endpoint, we'll definitely want to be able to filter on paid as well. It might be nice to filter on other information, but we can accept a PR that just filters on paid and iterate on it later.

**Acceptance Criteria:**

A request should be made to the `/search` endpoint like so:
```
http://127.0.0.1:5000/api/v1/search?language=python&category=books&paid=false
```

All the resources returned should contain `paid: false` in their object (i.e., no paid resources are returned).

If you search for `paid=true`, it should return all paid resources.

**Comment by mc962** [comment]
Would this mainly be passing new parameters to what looks like the Algolia service?
And if so, is there any special setup to be able to hit this service locally? (I keep getting an exception for the service being unreachable from my laptop, with the API run in a container, and looking at the .env file, I'm not sure those are real keys)

**Comment by aaron-suarez** [comment]
@mc962 If you'd like to contribute, feel free to add in language and category filters, those are still needed to be able to close this out 😄 I think the hardest part was done by Kandeel because now you can follow the same pattern for the other two and we're good

**Comment by mc962** [comment]
I can do that.

I think part of my issue (and why I didn't do anything for it at the time), was that I couldn't really connect to Algolia to confirm that things were working. Are there some sort dev credentials that we have for this?

**Comment by aaron-suarez** [comment]
We do not. People have just been signing up for a free trial and going from there. I can see about contacting them about dev credentials if you don't think you'll get it done within the 14 days of the trial
