### ISSUE TITLE
All errors should be a list of dicts containing `code` and `message` properties

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#196]
The API has a standard way of returning errors. It should conform to a certain schema. A correct example of this schema is returned when the `updated_after` filter is used improperly:
```json
{
    "apiVersion": "1.0",
    "data": null,
    "errors": [
        {
            "code": "unprocessable-entity",
            "message": "The value for \"updated_after\" is invalid"
        }
    ],
    "status": "Unprocessable Entity",
    "status_code": 422
}
```

One example of it being wrong is here:
https://github.com/OperationCode/resources_api/blob/48130749370071255bfd9a4a98de2315505412ac/app/api/routes.py#L112

Notice how this line of code causes a list of strings to be returned rather than a list of dicts conforming to the schema.

**Acceptance Criteria:**
Every `4xx` response from the API should contain an array of objects, each of which have a `code` and `message`. There may be additional information in there (such as `missing_params` for the 422 response), but `code` and `message` must be in there.

**Comment by guglielmo-andrew** [comment]
Hi @aaron-suarez! I am interested in helping tackle this issue. This is my first issue ever, but I've read the Contribution Guide and I think I could help here. I am a little unsure of the scope of the issue. I see the one line that returns a list with a single string. I think it is supposed to be `dict(errors="Invalid username or password")`. Are there likely more lines like this throughout the entire API? Thanks!

**Comment by aaron-suarez** [comment]
Yes indeed. Sending you a slack message so we can hash out the specific requirements

**Comment by aaron-suarez** [comment]
We determined a schema that we hope will be better than what was described in the original issue comment. Everything was standardized to the new schema in #185
