### ISSUE TITLE
Need GET /categories/{id} Route

### ISSUE THREAD

**Issue by soris-codes** [OperationCode/resources_api#198]
Currently getting a 404 for the `/categories/{id} endpoint.

**Comment by seoulstice** [comment]
I'd like to tackle this issue if no one has claimed it yet.

**Comment by seoulstice** [comment]
@aaron-suarez @soris-codes

**Comment by aaron-suarez** [comment]
Yeah go ahead and get it. I'll be happy to review the PR when you get it in

**Comment by seoulstice** [comment]
Thanks!

**Comment by aaron-suarez** [comment]
Closed with #208
