### ISSUE TITLE
CONTRIBUTING.md file doesn't include docker

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#201]
The CONTRIBUTING.md file has a list of technologies the project uses, but it's outdated. You actually don't need Postgres installed because we use docker now, but you definitely need docker installed, etc. That whole part of the file could use some updating with the latest information about the repo, and possibly more "getting started" stuff surrounding docker.

**Comment by the-bose** [comment]
Hello, I would like to contribute to this.

**Comment by aaron-suarez** [comment]
@the-bose It looks like @RanadeepPolavarapu kinda just swooped in there. Are you interested in any of our other open issues? I'll go ahead and get you assigned to one if you like

**Comment by the-bose** [comment]
I'll check the other issues out and see if I can help.

**Comment by Parikshit-Hooda** [comment]
@aaron-suarez  haha. I have an issue that I was thinking of opening but I would love for you to take it.
Issue 1 - Include MIT License in the README.md . What I mean by include is to include a link to the license in the current repo. Something like this : https://github.com/ladybug-tools/honeybee/pull/289

Issue 2 - Update LICENSE file in the repo to include coverage to 2019 too. Right not it says, 
  'Copyright (c) 2018 Operation Code'
Perhaps changes this to something like : 
'Copyright (c) 2018-2019 Operation Code'
