### ISSUE TITLE
Add `make docs` command

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#203]
Now that we have an OpenAPI file set up with Redoc, it would be nice to be able to view those docs when you're working with the code. We should add a `make docs` command that you can run and it will pull up the redoc. It should be based on the OpenAPI file 
here https://github.com/OperationCode/resources_api/blob/master/openapi.yaml

When you make changes to the file, you should be able to just refresh and then see your changes. This way, when you make changes to the requests/responses, making changes to the docs can be seamless.

**Comment by soris-codes** [comment]
I would like to help with this.

**Comment by aaron-suarez** [comment]
Turns out `make docs` is unnecessary, thanks for #204, which will close this out
