### ISSUE TITLE
Documentation - `Update Resource` endpoint returns a 401 and a 422 response as well

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#205]
The `Update Resource` endpoint documentation claims that it only returns a 200 or a 404:
![Screen Shot 2019-07-27 at 8 10 49 PM](https://user-images.githubusercontent.com/2008701/62000968-a626cb80-b0aa-11e9-960f-2420ccc5e980.png)
This endpoint will also return a 422 if the resource is invalid, and a 401 if you do not pass a valid API Key.

The OpenAPI file must be updated to add these responses. You should be able to just copy and paste from the `Create Resource` endpoint which does document these responses.

**Comment by soris-codes** [comment]
@aaron-suarez - Will fix this ASAP.
