### ISSUE TITLE
Test coverage for views

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#207]
We recently added documentation to the `/` route. We have no tests around those views. It would be nice to verify in the unit tests that they return valid responses so we can be sure that every deploy will have the docs correctly loaded.

![Screen Shot 2019-07-29 at 12 16 05 AM](https://user-images.githubusercontent.com/2008701/62023349-14948800-b196-11e9-9d70-2afd34b54612.png)

**Comment by the-bose** [comment]
Does the issue require a pull request to confirm the test result?

**Comment by teaglebuilt** [comment]
can i grab this issue?

**Comment by teaglebuilt** [comment]
Is there a need for a pytest fixture for the yaml file download? or just testing for successful status codes?

**Comment by aaron-suarez** [comment]
There is not a fixture. We definitely need to test for a successful status code, but it would also be nice to have a test that the content looks correct in some way. I'm honestly not sure what that might look like, so feel free to do whatever you think is best and we can talk about it.
