### ISSUE TITLE
Change 'paid' filtering in resources endpoint

### ISSUE THREAD

**Issue by Kandeel4411** [OperationCode/resources_api#222]
Currently if an invalid paid attribute is given to the `/resource` endpoint it will default to it being `false`, we would like it to default to `all` instead

**Examples**:
This currently defaults to `paid=false` to filter for the /resources endpoint:
```
http://127.0.0.1:5000/api/v1/resources?paid=trueeeeeeee
```
Returns all resource objects with `paid: false`

**Acceptance Criteria**:
```
http://127.0.0.1:5000/api/v1/resources?paid=trueeeeeeee
```
Should return all resources instead ( due to it not being strictly true/false case insensitive )

**Comment by Pachwenko** [comment]
I am looking into this
