### ISSUE TITLE
API Key Rotation and Revocation

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#225]
Currently, there is no way for users nor administrators to revoke an API key or rotate the API in the event of compromise. For more information about the use cases, see https://github.com/OperationCode/resources_api/issues/103#issuecomment-480605369.

I'm open to discussion on the best way to handle this. Typically (in my experience) an API is associated with a website that will require you to log in to manage keys. In our case, the API is a completely separate system from the operationcode.org website. We're working towards integrating them via the front end, but something like managing keys from the OC site would be a rather large engineering lift. Therefore, unless someone is extremely dedicated to this and can build out the functionality on the front end, the back end and the API, we're going to have to find a way to provide this functionality using only the API.

Keep in mind that the only way we currently have of authenticating users is via their Operation Code credentials. Currently, there is no concept of an "admin". This might require a slight redesign depending on if someone is clever enough to think of a way to incorporate the functionality in the existing system.

**Acceptance Criteria**

1) Users should be able to ask the API for a new API key (i.e., key rotation). The old key should become invalid when this action is performed.

2) Administrators should be able to perform key rotation for any API key. The interface should allow for rotating it based on email address or API key. This functionality may be safer as a click command rather than through the public API. Doing it as a click command should also solve the problem of us having no admin users, because only admins are able to access the click commands.

3) Administrators should be able to blacklist a user from using the API (i.e., "permanent" revocation). Then, even if that user is still a valid OC user, their API key is no longer valid and they will not be allowed to make another one. Again, this should probably be a click command.

If there are some other aspects of this that I missed, please feel free to comment on this issue with additional criteria. It's encouraged to break this out into multiple PRs for each of the acceptance criteria to avoid having an extremely large code change in one PR.

**Comment by dprothero** [comment]
I can take a crack at item 1 in your acceptance criteria.

Would you prefer a different endpoint, e.g. `/api/v1/new_apikey` or a new key in the JSON payload? e.g.

```js
{
  "email": "your@email.com",
  "password": "yoursupersecretpassword",
  "issue_new_key": true
}
```

(default being `false` if it's not provided)

Also, we're just overwriting their existing key? A more robust implementation -- i.e. a full rotation workflow -- would allow for requesting a new key, while keeping the old key active as well. You would then use a separate request to deactivate the old key once you've deployed the new key. That may be overkill for the use case, however.

**Comment by dprothero** [comment]
Looking at the code, I see what you mean by "click commands". `app/cli.py`, correct?

**Comment by aaron-suarez** [comment]
Yes we call them "click commands" because they use the Click package. See https://flask.palletsprojects.com/en/1.1.x/cli/ and https://click.palletsprojects.com/en/7.x/

**Comment by aaron-suarez** [comment]
@dprothero Regarding the other question, I would love to see the more robust implementation, but I think it would require some changes to the model as well as the `/apikey` endpoint because right now everything is built on the assumption that each user only has a single API key

**Comment by aaron-suarez** [comment]
I'm open to either a new endpoint such as `/new_apikey` or the `issue_new_key` flag, though I think the latter would be less of a lift. I'll leave it up to you to make the decision and open a pull request with the one you think is the better solution.
