### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#229]
**Background**
There have been no breaking changes since the first version was released, so this hasn't come up until now. I believe the best solution to #206 will require a breaking change to the API. That being said, when we make breaking changes to the API we'd like to allow for clients to use the older versions of the API so they have time to upgrade their integration to the new version. So we need a way to let the API determine which version is being requested and then return the response with the correct logic for that particular version.

**Description**
Requests should be able to include an `X-Api-Version` header specifying the version of the API the request is meant for. The API should then execute the logic for that particular API version and return the specific response. 

**Acceptance Criteria**
The API should accept an `X-Api-Version` header.
There should be a standardized way to put certain logic behind a newer API version.
The API should respond with an accurate version number for which logic was executed. Right now I think it just responds with 1.0 no matter what.

**Comment by Jitsusama** [comment]
I'm will to take a stab at this.

**Comment by Jitsusama** [comment]
@aaron-suarez; to clarify things, the APIs you want to version are all defined in _/app/api/route.py_ correct?

**Comment by aaron-suarez** [comment]
Yeah, but more generally, any response from our API is going to have a version along with it, which currently is sort of hard coded here https://github.com/OperationCode/resources_api/blob/master/app/__init__.py#L12

We want that instead to be variable, defaulting to the latest version, but if someone requests a specific API version we should support that.

**Comment by Jitsusama** [comment]
Cool, thanks for that additional information. I'm currently thinking of adding a new decorator that will take in some configuration specifying a mapping of versions to functions that will generate outputs. It would wrap the top level blueprint route and its parameter list will receive the generated output and the route's body can send it out. I'll obviously also have to think about how to handle outputting the version as well.

Does that sound good in theory?

Also, looking at the file you linked, I can't help but notice that you have a base URI for the blueprint that references a version number (_/app/v1_). Will it be confusing to have a separate version number specified in a header from what is already specified in the path? Also, what value does the path specified version number provide if it is not getting used to indicate new APIs? Are these going to refer to 2 separate versions (like one version for the whole solution and another specific to each endpoint?)

**Comment by aaron-suarez** [comment]
For the first part: I'm fine exploring the idea of a decorator, that could probably work. But I don't think it even needs to be that much overhead. I think that it would be more like `if` statements, where a version is mapped to some constant that you check against, so it would look like:
```python
def some_route():
     if api_version_1_1:
        do_something_for_1_1()
    else:
        do_the_thing_for_1_0()
```
and then of course we'd need to return `"apiVersion": "1.1"` in the JSON response if it goes the api_version_1_1 route.

For the second part: the idea is that if we have to bump a major version (e.g., 2.0) we're probably going to rewrite a bunch of business logic, so we'll just create a new set of folders for that version. I'm less concerned about what will happen when we hit a major version update and more concerned about allowing for minor version updates, like my 1.1 example above. It's not exactly semver, a version is only bumped when there are breaking changes. A major version is only bumped when it's basically a complete rewrite. I'd be willing to talk about other approaches, but it's not like we're distributing software for people to download and run on their machines. If we have a patch level change to make, we just patch it and we patch it for all versions. If we have a breaking change, we increment the minor version to separate it from the versions that came before.

Does that make sense?

**Comment by Jitsusama** [comment]
Yes, that does make sense. Hopefully the final question, are you wanting to have this implemented on each route, or would you like for me to just implement it on a representative route, as I’m assuming most routes do not require versioning (at least not yet?)

**Comment by aaron-suarez** [comment]
I think the acceptance criteria for this will be creating a centralized place where we can define such constants as `api_version_1_1`, a way to parse the incoming X-Api-Version header and respond to it, and ensuring we return the correct API version in the json response. Like you said, all of the routes are on 1.0 right now, there is no branching logic for 1.1

**Comment by Jitsusama** [comment]
@aaron-suarez; I've posted up a PR. The only thing I didn't include was a centralized place to define constants, though I did setup a default version number constant in a new _versioned_ module. If you are also wanting to be able to specify valid version ranges or something, I propose doing that in a separate PR.
