### ISSUE TITLE
Data Cleaning: Consolidate Synonyms within Categories

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/resources_api#24]
Very many categories have similar values ex: `Web Dev` and `Web Development` this example might be taken care of but we should be looking for these.

Acceptance criteria:

1. Create a click command to find potential matches that are similar enough. Use fuzzy string matching, or something of the like.
2. Include simple unit tests for known examples  as this is going to be more hit and miss.
3. Make the threshold configurable so that we can try with different strictness.

**Comment by aaron-suarez** [comment]
I think that Algolia takes care of the idea of fuzzy string matching. If it's not a featured category on the front end then it should be found via the /search endpoint. If we run into some more serious problems, we can reassess this.
