### ISSUE TITLE
Header shouldn't specify nginx version

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#249]
Right now, when you query resources.operationcode.org, the server responds with the specific version of nginx we're using. This information should not be given out freely. We should specify which headers nginx returns and make sure that the version we're running is not one of them.

**Comment by Kandeel4411** [comment]
We can hide this information by editing `/etc/nginx/nginx.conf` file by adding the server_tokens off line inside http configuration part like so:
```
http {

        ##
        # Basic Settings
        ##
        server_tokens off;
```
then restarting Nginx web server to apply the changes
[Reference](https://www.tecmint.com/hide-nginx-server-version-in-linux/)

**Comment by aaron-suarez** [comment]
Fixed by https://github.com/OperationCode/operationcode_infra/pull/141
