### ISSUE TITLE
Pin Unpinned Dependencies in requirements.txt

### ISSUE THREAD

**Issue by mc962** [OperationCode/resources_api#254]
## Motivation
As I was browsing through the project, PyCharm notified me that there were dependencies that it wasn't aware of (generally this happens when they aren't pinned in requirements.txt). Some of these dependencies are pretty important, like `flask` and `alembic`, and should be pinned to prevent potential issues between environments/installs.

## Changes
- Add unpinned projects to requirements.txt
- Remove unused imports

**Comment by mc962** [comment]
Unpinned Packages:
- flask
- python-dateutil
- pytest
- alembic

**Comment by aaron-suarez** [comment]
Thanks for making this issue @mc962 !

**Comment by aaron-suarez** [comment]
This bit me today... there was an updated version of `Werkzeug` released in January and it had a breaking change for how you import the function we use from it. We really need to get these pinned.
