### ISSUE TITLE
OpenAPI file naming convention issues

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#259]
We use an OpenAPI file to document our API, and there are a few issues with the naming conventions. As a matter of fact, it's almost like there are no naming conventions at all. Camel case and snake case are combined together in an odd fashion, and some of the names aren't very descriptive. Now that the document is formed, it would be good to take a look at the file as a whole and fix the naming issues.

See https://github.com/OperationCode/resources_api/pull/215#discussion_r352617465 and https://github.com/OperationCode/resources_api/pull/215#discussion_r352618239 for examples of the issues.

**Comment by avats-dev** [comment]
@aaron-suarez I want to work on this one. Can you list all the files and references where I need to make changes? Thanks.

**Comment by aaron-suarez** [comment]
@avats-dev The Open API file is here https://github.com/OperationCode/resources_api/blob/main/app/static/openapi.yaml

There isn't really clear acceptance criteria for this issue, just make some decisions about conventions that should be used (i.e., maybe we want to use PascalCase for component schemas) and then make everything conform to that convention.

One example is `ApiKeyResponse` and `ApiKeyResponse_data`
https://github.com/OperationCode/resources_api/blob/169e045a0d2fa3cdf68a85b16d47238ba2477949/app/static/openapi.yaml#L1160
https://github.com/OperationCode/resources_api/blob/169e045a0d2fa3cdf68a85b16d47238ba2477949/app/static/openapi.yaml#L1174

Nowhere in programming does it make sense to use PascalCase and snake_case for the same thing (in this case, for a component schema). So perhaps is should be changed to `ApiKeyResponseData` to make it a little more conventional.

Similarly, `Resource_list` should probably be changed to `ResourceList` https://github.com/OperationCode/resources_api/blob/169e045a0d2fa3cdf68a85b16d47238ba2477949/app/static/openapi.yaml#L1079

If you go through the file, you'll see examples of this all over the place.

Another issue with the OpenAPI file conventions is that there are components with names that don't really match what they are. For example `Error_list` is an object
https://github.com/OperationCode/resources_api/blob/169e045a0d2fa3cdf68a85b16d47238ba2477949/app/static/openapi.yaml#L833-L834

Besides the fact that it should be `ErrorList`, it really should be called `list` at all because it's not a list (not an array). It's an object, so maybe `ErrorResponse` would be more appropriate. 

Someone just needs to go in and think about what these things are and name them properly, using a uniform convention for the casing. As they say, naming things is the hardest part of programming 😅 If you're up for it, then feel free to go in and change those names.

We'll accept any improvements in these areas, so don't feel the need to make everything perfect. Make some small improvements to help it get closer, and we can leave the issue open until it's all cleaned up over time.

**Comment by avats-dev** [comment]
@aaron-suarez thanks for this, great explanation. Also, I'm going with `camelCase` as it is more common and also then there would be no need to change existing single word names.

**Comment by king-11** [comment]
@aaron-suarez I did some work on this issue too but am not able to send in a PR as a prior one is there :sweat_smile:
