### ISSUE TITLE
resource suggestion - up-for-grabs

### ISSUE THREAD

**Issue by andy5995** [OperationCode/resources_api#274]
I suggested this in Slack, raZ0r agreed it would be a good resource

https://up-for-grabs.net/

> This is a list of projects which have curated tasks specifically for new contributors. These are a great way to get started with a project, or to help share the load of working on open source projects.

**Comment by aaron-suarez** [comment]
Hi @andy5995! If you'd like to add it as a resource, please use the API to do so. The documentation for adding it via the API is here https://resources.operationcode.org/#tag/Create-Resources/paths/~1resources/post

Basically you just `POST https://resources.operationcode.org/api/v1/resources` with your JSON payload.

Alternatively, feel free to post the link in slack and react to it with a 💾 emoji, which will put it in #digest where I'll add it to the API on my next iteration of that.

Going to close this issue out, thanks for your suggestion!
