### ISSUE TITLE
Investigate issue with Rate Limiting

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#279]
The rate limiting logic has caused the healthchecks from EKS to cause a denial of service to all clients of the API. More investigation is needed, but it looks like we need two fixes:
1) Whitelist the IP address spaces of EKS so it doesn't get rate limited
2) Ensure that when rate limiting happens, only the problematic client gets rate limited, not all clients everywhere. The whole point of rate limiting is to prevent denial of service, not cause it 😅

**Comment by irvingpop** [comment]
Let's just not have a rate limit for `/healthz`, I think that would solve the operational issues

**Comment by aaron-suarez** [comment]
Alright, to remove rate limiting, it looks like we need to add `@limiter.exempt` to that particular endpoint. Then we need to figure out whether rate limiting applies to all clients and make that not the case
