### ISSUE TITLE
GET /resources Route should take query params for language and category

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#29]
The original vision of routes was flawed. We originally wanted to have routes called `GET /categories/{category}` and `GET /languages/{language}` to get all of the resources for a category and language. After some discussion, @wimo7083 and I decided that it makes much more sense to have the single route for `GET /resources` take optional query parameters specifying the category and language. So a valid request to this endpoint can take `page`, `page_size` (these two are addressed in #21) as well as `language` and `category`. So the request might look something like this:

`GET /resources?category=books&language=ruby&page=2&page_size=5`

This issue will be considered fixed when the query params for `language` and `category` are accepted by the endpoint and return the filtered results.

**Comment by heavysaturn** [comment]
agreed. I will update #28 to do this instead.

**Comment by aaron-suarez** [comment]
This was fixed in #42
