### ISSUE TITLE
Need GET /languages Route

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#32]
This endpoint should get the list of languages and should implement pagination in the same manner as the patterns already implemented in the /resources endpoint (See #21)

**Comment by michizhou** [comment]
@aaron-suarez I would like to take this issue!

**Comment by wimo7083** [comment]
Sure, good luck, let us know you have any issues.

Placeholder myself.

**Comment by aaron-suarez** [comment]
Ok, just give me a day or two to get #21 taken care of, then implement the pagination in the same manner for this issue.

In the meantime, if you haven't already joined our slack team, you can join the conversation in the #oc-python-projects channel. Just sign up for slack via operationcode.org/join

**Comment by aaron-suarez** [comment]
The interface to the paginator changed and now doing `GET api/v1/languages` always returns an empty list.

We need to get the query to pass into `language_paginator.items` and take the `Language` argument out of the Paginator constructor.

**Comment by michizhou** [comment]
@aaron-suarez How do you think we should do that? Should we just change the Paginator constructor call and its implementation or do we need to do something more?

**Comment by michizhou** [comment]
@aaron-suarez Now that #39 has been merged, how do we think we should approach this? Should we just change the Paginator constructor call and its implementation or do something more?

**Comment by michizhou** [comment]
@aaron-suarez I just created a new PR to deal with this reopened issue's concerns. Feel free to look over my changes and share your thoughts in a review.
