### ISSUE TITLE
Need POST /resources Route

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#33]
This endpoint should create a new resource based on JSON form data sent with the POST.

*Required attributes*:
`category` - A string category. Endpoint should add it to existing category or create a new category if necessary
`languages` - An array of strings representing each language associated with this resource. Endpoint should add any new languages to the languages table and associate this resource with any existing languages that are specified
`name` - A string that's the name of the resource
`url` - A string that is a valid URL. (Ideally, the endpoint would validate this URL by performing a GET request and ensuring it receives a 200 response, but that's not really necessary for the MVP, just something to think about)

*Optional attributes*:
`paid` - Boolean. True if the resource requires payment to use. False if it's a free resource. Defaults to false
`notes` - String. Any notes that are relevant to the resource

**Comment by aaron-suarez** [comment]
It should return the created resource

**Comment by michizhou** [comment]
@aaron-suarez I have opened a PR that should solve this issue (see #39). Please let me know if you need me to make any changes. Thanks!
