### ISSUE TITLE
Return "Getting Started" resources first when no parameters specified

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#338]
When the user first arrives at the Resources page on the front end, they are presented with whatever resources the database happens to serve up. Since we don't yet have featured categories on the front end, it would be nice to go ahead and serve up some resources that are relevant for beginners who maybe have no idea where to start on their learning journey. There are a bunch of great blog posts and similar "Getting Started" materials in the `Getting Started` category. From there, they can search for what they want, or filter by categories/languages. 

Acceptance criteria: When a request is made without any filter parameters to the `GET /resources` endpoint, the API should return "Getting Started" resources, followed by all the other resources available (paginated).

This should be able to be accomplished by adding an ORDER BY clause in this particular case. I have an idea adapted from this [stackoverflow post](https://stackoverflow.com/a/6332081):
```SQL
ORDER BY
   CASE category
      WHEN 'getting started' THEN 1
      ELSE 2
   END, id
```

I have no idea how to do this with Flask-SQLAlchemy, but we'll figure it out. Importantly, we shouldn't add this ORDER BY clause unless there are no other parameters at all. So we'll want some unit tests around this. I don't think it needs to be added to the documentation so we can skip making changes to the openapi.yaml file.

**Comment by Digbigpig** [comment]
I found a good example for this in SQLAlchemy. https://stackoverflow.com/a/17494735
I think this can be implemented within an if statement [somewhere around here.](https://github.com/OperationCode/resources_api/blob/37ab0b449ff180432237c6884370f9e14d56f91e/app/api/routes/resource_retrieval.py#L46)

**Comment by jtmst** [comment]
Oh nice!  I'll try and implement that tomorrow during lunch. Thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
