### ISSUE TITLE
Need PUT /resource/{id} Route

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#34]
This endpoint should update a resource based on the id passed in and JSON form data given in the request.

*Required attributes*:
`id` - Integer. The id of the resource to update.

*Optional attributes*:
`category` - A string category. Create a new category if necessary, switch the association of this resource to the new category
`languages` - An array of strings representing each language associated with this resource. Endpoint should add any new languages to the languages table and associate this resource with any existing languages that are specified  
`name` - A string that's the name of the resource  
`url` - A string that is a valid URL. (Ideally, the endpoint would validate this URL by performing a GET request and ensuring it receives a 200 response, but that's not really necessary for the MVP, just something to think about)
`paid` - Boolean. True if the resource requires payment to use. False if it's a free resource
`notes` - String. Any notes that are relevant to the resource

**Comment by aaron-suarez** [comment]
It should return the updated resource

**Comment by michizhou** [comment]
@aaron-suarez I have opened a PR that should solve this issue (see #38). Please let me know if you need me to make any changes. Thanks!
