### ISSUE TITLE
Languages/Categories should delete themselves if they no longer exist

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#344]
Suppose we have a language called `CSS/Bootstrap` and then someone realized that that's two languages and then changes the languages for that resource to be `["CSS","Bootstrap"]` instead. What happens to the language `CSS/Bootstrap`? Well, it gets orphaned. It exists, but there are not resources that have that language.

I think that whenever a resource is updated and the `languages` attribute is one of the changes, we should check that the old languages still exist on some resource. If they do not, then we should delete the language.

Same thing with categories. If a category gets removed from the last resource with that category, then the category should be deleted as well.

**Comment by mike-lloyd03** [comment]
@aaron-suarez any problems with me assigning myself to this one?

**Comment by aaron-suarez** [comment]
No problem at all. Were you there in the meeting when I was going over this one and what it's about? If not, that's fine, just ask if you have any issues.

**Comment by mike-lloyd03** [comment]
No I wasn't in the meeting but I think I got it. I'll let you know if I need any pointers.

**Comment by king-11** [comment]
@aaron-suarez is the issue resolved I can start working on it if not?

**Comment by mike-lloyd03** [comment]
The code works as written right now but unit tests are needed to cover the new functionality.

**Comment by king-11** [comment]
ohh got it @mike-lloyd03 so if the tests are needed I can start working on it if it's alright?

**Comment by mike-lloyd03** [comment]
Go for it.

**Comment by king-11** [comment]
@mike-lloyd03 i wrote some tests but it doesn't seem to work can you have a look

```python
def test_delete_unused_languages(module_client, module_db, fake_auth_from_oc, fake_algolia_save):
    client = module_client
    apikey = get_api_key(client)

    # Happy Path
    response = update_resource(client, apikey)
    assert (response.status_code == 200)
    assert (response.json['resource'].get('name') == "New name")

    #Initial Data
    name = "Language Test"
    url = None
    category = None
    languages = ["Java", "JS/TS"]
    paid = None
    notes = None

    response = update_resource(client,
                               apikey,
                               name,
                               url,
                               category,
                               languages,
                               paid,
                               notes)
    assert (response.status_code == 200)
    assert(response.json['resource'].get('name') == "Language Test")

    languages_response = response.json['resource'].get('languages')
    assert("Java" in languages_response)
    assert("JS/TS" in languages_response)

    languages = ["Java", "Javascript", "Typescript"]
    response = update_resource(client, apikey, name, url,
                               category, languages, paid, notes)
    assert(response.status_code == 200)

    languages_response = response.json['resource'].get('languages')
    assert("Java" in languages_response)
    assert("Javascript" in languages_response)
    assert("Typescript" in languages_response)
    assert("JS/TS" not in languages_response)

    db_languages = client.get('api/v1/languages')
    db_languages = [language.get('name') for language in db_languages.json['languages']]
    # assert(isinstance(db_languages, list))
    assert("JS/TS" not in db_languages)
```
It's failing on the last assertion :(

**Comment by aaron-suarez** [comment]
@king-11 I haven't ran your test yet, but I would expect that last test to fail because we haven't yet written the code to have the languages delete themselves if they no longer exist. Did you try this on `main` or on @mike-lloyd03's branch?

**Comment by mike-lloyd03** [comment]
@aaron-suarez Languages should auto-delete as well. My last commit implemented that logic.

**Comment by aaron-suarez** [comment]
@mike-lloyd03 would you mind adding that test to #362 so we can get it merged? IIRC, the tests were what we were waiting on.

@king-11 if you want credit for writing this test, go ahead and commit it on a branch and then I'll show @mike-lloyd03 how to cherry-pick it off the branch and stick it on his PR. If you don't care one way or the other how the code makes its way in there, then he can just copy and paste it into there and push up his own commit with your test in there

**Comment by king-11** [comment]
@aaron-suarez created the PR and yeah now it just fails on the last assertion until the changes are made

**Comment by aaron-suarez** [comment]
Cool I'll get with @mike-lloyd03 about cherry-picking your commit and sticking it on his PR so that way we can get that merged. If he's unavailable, I'll just do it myself since I think I have the power to edit either of your PRs
