### ISSUE TITLE
Beginner issue: README.md instructions should have user pull up docs pages

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#371]
In the last step of the "Getting Started" section of the README, we have the user navigate to http://localhost:5000/api/v1/resources and then say "If you see some JSON with a bunch of resources, it worked!"

https://github.com/OperationCode/resources_api/blame/main/README.md#L36-L38

I think it would be better to go ahead and have them navigate to `http://localhost:5000` directly and then say that they should see the documentation. This will prompt them to start reading the documentation and understand how it works, as well as let them know that we have documentation they need to keep updated if they contribute a change that would make the docs outdated.

**Comment by avats-dev** [comment]
@aaron-suarez I'm taking up on this. Thanks:tada:
