### ISSUE TITLE
Duplicate typescript search item in languages field for resource search by language

### ISSUE THREAD

**Issue by Matt-st** [OperationCode/resources_api#377]
# Bug Report
## What is the current behavior?
The current behavior is that 2 items show up for the language "typescript" when searching by language.

## What is the expected behavior?
There should only be one option that shows up in the languages search field for "typescript". 

## What steps did you take to get this behavior?
I went to this [page](https://operationcode.org/resources/1?languages=c%23) and typed in "typescript" which returns 2 results as you can see below.
<img width="1102" alt="Screen Shot 2020-09-26 at 11 01 11 AM" src="https://user-images.githubusercontent.com/5315523/94343735-2f57cc00-ffe8-11ea-9c43-bdc9a690b640.png">

### Browser
google chrome
### Is This A Third-Party Issue?

Don't know

**Comment by kylemh** [comment]
Good find, @Matt-st 

I moved this into the Resources API repo.

**Comment by aaron-suarez** [comment]
@Matt-st I just fixed the issue with the duplicate typescript language in prod. Do you want to take a stab at fixing the API to add a deduplicate constraint?

**Comment by king-11** [comment]
@aaron-suarez can I work on this issue as it seems inactive for awhile

**Comment by aaron-suarez** [comment]
@king-11 yes, please take this on. I have no intention of adding de-duplication logic myself, and I suspect that neither does @Matt-st 

It is a welcome change, however. Please submit your PR 😄

**Comment by king-11** [comment]
@aaron-suarez need a bit of clarification so I was thinking converting list inside get_languages to a set will help 🤔 but regarding that no allowing addition of different capitalisation in table for same language where is that part?

**Comment by aaron-suarez** [comment]
@king-11 This function is the part that gets the list of languages from the request (specifically a resource creation or resource modification request) and formats it in a way that it can be added to the Resource. 

https://github.com/OperationCode/resources_api/blob/main/app/api/routes/helpers.py#L18-L32

We'll need to add de-duplication checks in there
