### ISSUE TITLE
Make rollbacks a bit cleaner

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#5]
Something like this 

```
@app.teardown_request
def teardown_request(exception):
    if exception:
        db.session.rollback()
    db.session.remove()
```

http://flask.pocoo.org/docs/1.0/api/#flask.Flask.teardown_request

**Comment by wimo7083** [comment]
Acceptance criteria

1. Install handler for teardown request - attempt any cleanup that should happen on good state
2. Install handler for unhandled exception - attempt any cleanup that should happen on bad state
3. Install handler for not-found route (404).
