### ISSUE TITLE
Adding Linux setup instructions to Readme.md

### ISSUE THREAD

**Issue by Derek52** [OperationCode/resources_api#58]
Hi, I'm a Linux user, and would like to add Linux setup instructions under the mac instructions in the Readme. Would this be a helpful addition? Or do you find this unnecessary? I will admit the number of beginner programmers using Linux is pretty small.

**Comment by aaron-suarez** [comment]
I think it would be a helpful addition. With the exception of how you download Postgres, is there any difference from the Mac instructions?

**Comment by Derek52** [comment]
Starting Postgres is different. You also have to enable Postgres as a system service, to make sure it will automatically start itself after a reboot.

**Comment by aaron-suarez** [comment]
Ok, so I agree that Linux users are not going to be super beginners that need to be hand-held through each setup step. If you want to write a Linux section, I would think it would be enough to just highlight the differences and point out the important bits like the environment variables.

Feel free to open a PR and I'll review it.

**Comment by Derek52** [comment]
Ok, sounds like a plan. I'll just have them refer to the steps in the mac section, once the DB is created. I'll submit my PR sometime this evening/tonight.
