### ISSUE TITLE
Readme doesn't give instructions on forking and cloning

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#90]
When we changed the instructions from using `pip` directly to using docker, we didn't include the instructions about forking and cloning. We need to put these back in the README.

**Comment by itsaudia** [comment]
Can I claim this issue?

**Comment by aaron-suarez** [comment]
Sure! I will assign to myself as a placeholder for you. Hit me up on slack if you need any help with git.

**Comment by itsaudia** [comment]
I tried

**Comment by aaron-suarez** [comment]
Fixed by #93
