### ISSUE TITLE
README is missing `make` commands

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#98]
There are a bunch of useful `make` commands that are available via the Makefile, but not all of them are called out. There should definitely be a call out for `make test` which will run all of the tests. Any of the other extremely common make commands should also be called out. There should also be a statement that more commands than just the common ones exist in the makefile, and contributors should go ahead and take a look at it.

Thanks to @SkyelahBay for making me aware of this issue.

**Comment by wimo7083** [comment]
I think that instead of trying to have documentation track each command we should have our documentation point to the source (Makefile), and then make what's happening in them clear enough so we don't fall out of date.

**Comment by aaron-suarez** [comment]
Agreed. I just wanted to make sure that we specifically put `make test` in there because we want our contributors to be able to run the tests before they commit/push/PR

**Comment by wimo7083** [comment]
Acceptance Criteria:

1. Readme should include steps to run resources api locally
2. Readme should include steps to develop resources api
3. Readme should more detailed steps for authentication to include how to get username and password for operation code.

**Comment by gagandeepp** [comment]
@wimo7083  Assign this to me if it is still open?

**Comment by dprothero** [comment]
I'm working on some other enhancements to the README, so I can take this.

**Comment by aaron-suarez** [comment]
Thanks @dprothero!
