### ISSUE TITLE
Linter allows ending file without a newline

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#99]
All of our files should end with a newline character. The linter currently will pass when there is no newline at the end of the file. We need to tweak these settings a bit to include that check.

**Comment by wimo7083** [comment]
```
for i in * ; do  echo $i; \
 if diff /dev/null "$i" | tail -1 | \
  grep '^\\ No newline' > /dev/null; then echo >> "$i"; \
 fi; done
```
https://stackoverflow.com/questions/3261925/how-to-fix-no-newline-at-end-of-file-warning-for-lots-of-files

https://help.github.com/en/articles/dealing-with-line-endings

Once we get it into a good state and config we can probably have the linter require proper endings.

**Comment by aaron-suarez** [comment]
Flake8 (our linter) should be catching this with https://lintlyci.github.io/Flake8Rules/rules/W292.html

This might take some actual troubleshooting to figure out why it's not catching this already...

**Comment by aaron-suarez** [comment]
I tried just now removing the newline from the end of a few random files within `app` and `app/api` and the linter caught it all with W292. I'm not sure what the problem was before, but it appears this is no longer an issue.
